### ISSUE TITLE
HttpClient timeout

### ISSUE THREAD

**Issue by mofolom** [coryrwest/B2.NET#10]
Good work on the api, thanks.

Would you make httpclient's timeout a configurable parameter? It times out after the default 100 seconds.

**Comment by omrikaufman** [comment]
i am having this issue as well ,
when uploading large files :)
cory is the best he will fix it  in no-time

**Comment by mofolom** [comment]
so, you can clone the repo, then modify HttpClientFactory.CreateHttpClient() to take a parameter that sets the httpClient's timeout prop. Then do a pull request.

**Comment by coryrwest** [comment]
I have the change ready, just doing some testing.

**Comment by coryrwest** [comment]
Released in 0.4.6 on nuget.

**Comment by mofolom** [comment]
good man.

**Comment by omrikaufman** [comment]
as i said cory is the best ,
thanks cory :)
