### ISSUE TITLE
B2Net.Models.B2Exception c000_v0001059_t0024 is too busy

### ISSUE THREAD

**Issue by mofolom** [coryrwest/B2.NET#11]
I have a service that uploads a 10mb file to object storage. It does this every 3 minutes. Typically, an upload takes anywhere between 4-15 seconds. The uploads work well for a good part of the day but every so often it would fail with this exception. I have seen this happen for the past 6 days.

I haven't gone into the code to check. Maybe you know something about this?

![image](https://user-images.githubusercontent.com/4580013/36214713-e1cd63c6-11b2-11e8-8657-777020c8f519.png)

**Comment by coryrwest** [comment]
Can you paste the code that is doing the upload here? This looks like a B2 error. The node that you are uploading to cannot accept the upload because it is too busy. Usually getting a new uploadurl and using that will solve this, but I would like to see how you are uploading to confirm.

**Comment by mofolom** [comment]
Each upload action creates a new instance of this. 

![image](https://user-images.githubusercontent.com/4580013/36226628-0b5cce7e-11d7-11e8-8885-fc7d5303b99f.png)

**Comment by coryrwest** [comment]
This will happen sometimes with uploads if in the time it takes to get the `uploadUrl` and start the upload the server gets overloaded with requests. The best thing to do for now is to wrap the `Upload` in a try-catch and run the upload method again on failure. Using the `Upload` method you are using will "refresh" the `uploadUrl`, which should give you a different node to upload to and resolve this error. 

I have some ideas in place to solve this issue internally in the API, but have not had time yet to flesh them out.

**Comment by mofolom** [comment]
Thanks Cory. I will try refreshing the `uploadUrl`. In the meanwhile you could let us know what you thinking about solving this on the API side. Maybe we can help.

**Comment by coryrwest** [comment]
I am trying to think up some sort of retry mechanism that triggers on a failed upload when the error message indicates that the node is not available for upload anymore. Something similar to the auto-retry on the newer Upload methods, but less jenky.

When we get certain error messages from the B2 api, we know with some certainty that getting a new uploadUrl will solve the problem. I have not thought of a good way to handle this yet. I have started gathering my thoughts in issue #5.
