### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by utarn** [coryrwest/B2.NET#14]
Error:
I got this error when uploading the file.

An unhandled exception occurred while processing the request.

FormatException: The format of value "4_001a40cddf2c4b70000000000_0184e5f8_da6677_acct_--ObgNwZn8YYuv-rPa7cqujc1QU=" is invalid.

It seems that value is the authorization token.

Step to produce:
 _options = options;
_client = new B2Client(B2Client.Authorize(_options));
B2File result = await _client.Files.Upload(data, Guid.NewGuid().ToString() + "." + extension, _options.BucketId);

Version:
ASP.NET Core 2.0
B2NET 0.5.2

**Comment by coryrwest** [comment]
This will be fixed in 5.2.1 which I will release today probably.
