### ISSUE TITLE
"Only 'http' and 'https' schemes are allowed.\nParameter name: value" when trying to use GetDownloadAuthorization

### ISSUE THREAD

**Issue by welkie** [coryrwest/B2.NET#17]
I'm trying out the library and the first thing I did was upload a file to the bucket manually (called `bg.jpg`) and then tried to use the library in code to get a download authorization token. I have the following code:

```csharp
var result = await _b2.Files.GetDownloadAuthorization(
    "bg.jpg",
    30,
    Environment.GetEnvironmentVariable("B2_BUCKET_ID"),
    ""
);
```

The environment variable has my numeric bucket ID that was randomly assigned when I created the bucket.

When I run this code, it throws an `ArgumentException` which looks like it comes from the HTTP libraries internal to .NET Core. The message inside is `"Only 'http' and 'https' schemes are allowed.\nParameter name: value"`. I was wondering if anyone could help me with this? I don't see any spot in the API of the library to indicate protocol, so I'm confused as to why it's complaining about this.

Platform:
OS: Antergos
.NET Core SDK: 2.1.301

Contents of `csproj` file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="B2Net" Version="0.5.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

**Comment by welkie** [comment]
Fixed my issue. I should have read the instructions better. Forgot to authorize as I instantiated the client. Had to change this:

```csharp
services.AddScoped<IB2Client>(sp =>
{
    return new B2Client(new B2Options()
    {
        AccountId = Environment.GetEnvironmentVariable("B2_ACCOUNT_ID"),
        ApplicationKey = Environment.GetEnvironmentVariable("B2_APPLICATION_KEY"),
        BucketId = Environment.GetEnvironmentVariable("B2_BUCKET_ID"),
        PersistBucket = true
    });
});
```

to this:

```csharp
services.AddScoped<IB2Client>(sp =>
{
    return new B2Client(B2Client.Authorize(new B2Options()
    {
        AccountId = Environment.GetEnvironmentVariable("B2_ACCOUNT_ID"),
        ApplicationKey = Environment.GetEnvironmentVariable("B2_APPLICATION_KEY"),
        BucketId = Environment.GetEnvironmentVariable("B2_BUCKET_ID"),
        PersistBucket = true
    }));
});
```

**Comment by coryrwest** [comment]
I'm glad you figured it out. I am working on ideas to make it easier to authenticate and have the library handle that for you when it needs it.
