### ISSUE TITLE
"Only 'http' and 'https' schemes are allowed.\nParameter name: value" when when using non-master application key

### ISSUE THREAD

**Issue by welkie** [coryrwest/B2.NET#18]
This is a similar issue (https://github.com/coryrwest/B2.NET/issues/17) to the one I created not long ago. I'm getting the same error message but the situation is different. For a bit of context here, Backblaze now officially supports application keys and have launched the application key API endpoints. The term "master application key" is used to refer to what used to be called the "master key".

I have no problem using the `B2Client` methods if I `Authorize` using my master application key, but if I use any other application key, ones that I create specifically for my applications to use, I get this error message from an inner exception. I tried creating application keys with and without expiry, each with full read and write access to the one bucket I was working with, and the problem still occurred. I tried specifying the bucket ID (the same one the key has full access to) both as I `Authorize`d the `B2Client` and as I performed the operations, like `GetUploadUrl`. Problem still occurred.

I was wondering if this could be related to the library not having support for application keys (in fact I remember reading that the author has no intention of supporting those features). But this problem does confuse me a bit since these application keys should be the same as the keys used before, as far as I know, just with limited power.

**Comment by coryrwest** [comment]
I did not initially plan on supporting the keys API because at the time I didn't feel it was necessary. I might reconsider that when I have some more time to work on this. In the meantime there is a bug in the library that will prevent the Authorize method from automatically setting various required configuration values. I will release a fix soon fixing that bug, which should allow you to use normal Keys the same as Master keys.

**Comment by coryrwest** [comment]
Fixed in 0.5.32

**Comment by welkie** [comment]
Thanks for fixing that so quickly for me. I'll report back after I test it soon.

**Comment by welkie** [comment]
@coryrwest 

This works now, it can get connect with my application key. But I seem to be experiencing a regression now. It fails with `B2Exception: required field bucketId cannot be null` even when I set up my client with the default bucket ID:

```csharp
services.AddScoped<IB2Client>((sp =>
{
    return new B2Client(B2Client.Authorize(new B2Options()
    {
        AccountId = Environment.GetEnvironmentVariable("B2_CLOUD_STORAGE_APPLICATION_KEY_ID"),
        ApplicationKey = Environment.GetEnvironmentVariable("B2_CLOUD_STORAGE_APPLICATION_KEY"),
        BucketId = Environment.GetEnvironmentVariable("B2_CLOUD_STORAGE_BUCKET_ID"),
        PersistBucket = true,
    }));
}));
```

```csharp
var url = await _b2.Files.GetUploadUrl(); // throws exception
```
