### ISSUE TITLE
Large files upload (Opinion)

### ISSUE THREAD

**Issue by JM63** [coryrwest/B2.NET#24]
I'm having some difficulty uploading large files, with issues such as energie breaks, computer shutdown before upload completes, etc...

I'm thinking making some changes in my upload method by doing the following. Instead of putting the parts in a List<byte []>, save all the parts in a directory into text files, after that then began to upload each of the parts, deleting .txt part files after successful upload. 

So in case the pc was disconnected i could restart the process sent only the missing parts until all parts are uploaded and then Finish the file in Backblase B2 server.

I would like your opinion on whether this process could work or will be impossible.

Other opinions to solve this problem are welcome

**Comment by coryrwest** [comment]
@JM63 That seems like a fine solution. If you have access to the whole file before upload (i.e. You're uploading from the machine that the files exists on) you can check if the file is already in progress using [b2_list_unfinished_large_files](https://www.backblaze.com/b2/docs/b2_list_unfinished_large_files.html) (`Client.LargeFiles.ListIncompleteFiles` in the library) and then if you find it you can check [b2_list_parts](https://www.backblaze.com/b2/docs/b2_list_parts.html) (`Client.LargeFiles.ListPartsForIncompleteFile` in the library) to figure out what part you are on. Then you don't have to store the file parts and deal with keeping track of them.

**Comment by JM63** [comment]
I took a slightly different approach, but it seems to work fine, I leave here the code for whoever wants to test or bring us some improvements.

``   public static void PrepareLargeFileToUploadB2(string fileFullName_)
        {
            var cachefolder = new DirectoryInfo(@"C:\TEMP");

            var cloudparts = new CloudPartsInfo(fileFullName_);
            using (FileStream fileStream = File.OpenRead(fileFullName_))
            {
                byte[] bpart = null;
                long fileSize = fileStream.Length;
                long totalBytesParted = 0;
                long minPartSize = 1024 * (5 * 1024);
                int partnumber = 0;

                while (totalBytesParted < fileSize)
                {
                    var partSize = minPartSize;
                    // If last part is less than min part size, get that length
                    if (fileSize - totalBytesParted < minPartSize)
                    {
                        partSize = fileSize - totalBytesParted;
                    }

                    bpart = new byte[partSize];
                    fileStream.Seek(totalBytesParted, SeekOrigin.Begin);
                    fileStream.Read(bpart, 0, bpart.Length);

                    partnumber++;
                    string hash = Utilities.GetSHA1Hash(bpart);
                    cloudparts.PartsHash.Add(hash);

                    File.WriteAllBytes(cachefolder.AddFileName("part" + partnumber.ToString("D4") + ".dat").FullName, bpart);

                    totalBytesParted += partSize;
                }
            }
            cloudparts.SerializeToXmlFile(cachefolder.AddFileName("part0000.dat").FullName);
        }

 public static async Task<string> UploadFileFromCacheB2Async(string bucketFolder_)
        {
            // Verifica existencia de ficheiros na pasta de cache
            // caso não exitam sai
            var cachefolder = new DirectoryInfo(@"C:\TEMP");
            var files = cachefolder.GetFiles("part*.dat");
            if (files.Length <= 0) return String.Empty;

            // Verifica a existencia do ficheiro de informação adicional a sua não existencia pressupoe a não existencia de ficheiros por tal limpa a chache
            var infofilepath = cachefolder.AddFileName("part0000.dat");
            if (!infofilepath.Exists)
            {
                cachefolder.Clear();
                return String.Empty;
            }
            // Se o ficheiro de informação adicional não for valido ou se o numero de tentativas de envio for superior a 15 
            // limpa a chache para novo inicio de todo o processo de envio
            var infoparts = XmlHelper.DeserializeFromFile<CloudPartsInfo>(infofilepath.FullName);
            if (infoparts == null || infoparts.SendAttempts > 15)
            {
                cachefolder.Clear();
                return String.Empty;
            }

            B2File start = null;
            B2File finish = null;
            try
            {
                //List<B2File> filestodelete = new List<B2File>();
                var client = new B2Client(_b2AccountId, _b2ApplicationKey);

                if (string.IsNullOrWhiteSpace(infoparts.FileId))
                {
                    // Inicia o upload para B2 obtendo o id do ficheiro e guarda-o para eventual reinicio
                    start = await client.LargeFiles.StartLargeFile(bucketFolder_ + Path.GetFileName(infoparts.FilePath), "", _b2BucketId);
                    infoparts.FileId = start.FileId;
                }
                infoparts.SendAttempts++;
                infoparts.SerializeToXmlFile(infofilepath.FullName);

                foreach (var file in files)
                {
                    var index = file.Name.substring(4, 4).toInt();
                    // This is information file
                    if (index <= 0) continue;

                    var part = File.ReadAllBytes(file.FullName);
                    var partcount = infoparts.PartsHash.Count;

                    var logs = String.Empty;
                    // Try to send each part 3 times
                    for (int x = 0; x < 3; x++)
                    {
                        try
                        {
                            logs += $"{DateTime.Now.toDateTimeString()} Iniciou: Part ({index.toString()}/{partcount})";

                            var uploadUrl = client.LargeFiles.GetUploadPartUrl(infoparts.FileId).Result;
                            var partResult = client.LargeFiles.UploadPart(part, index, uploadUrl).Result;
                            if (partResult != null)
                            {
                                logs += $"\n{DateTime.Now.toDateTimeString()} Terminou Part ({partResult.PartNumber.toString()}/{partcount}), Tamanho:{partResult.Length.toString()}";
                                file.Delete();
                            }
                            break;
                        }
                        catch (AggregateException exa)
                        {
                            foreach (var errInner in exa.InnerExceptions)
                            {
                                logs += $"\n{DateTime.Now.toDateTimeString()} ERRO Part ({index.toString()}/{partcount}), Mensagem:{ exa.Message}";
                            }
                            if (x > 3) throw;
                            continue;
                        }
                        catch (Exception ex)
                        {
                            logs += $"\n{DateTime.Now.toDateTimeString()} ERRO Part ({index.toString()}/{partcount}), Mensagem:{ ex.Message}";
                            if (x > 3) throw;
                            continue;
                        }
                    }
                }

                finish = await client.LargeFiles.FinishLargeFile(infoparts.FileId, infoparts.PartsHash.ToArray());
                infofilepath.Delete();
            }
            catch (AggregateException exa)
            {
                foreach (var errInner in exa.InnerExceptions)
                {
                    Console.WriteLine(exa.Message);
                }
                throw;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
           
            return (infoparts.FileId == finish.FileId) ? finish.FileId : null;
        }

  public class CloudPartsInfo
    {
        [XmlElement(ElementName = "File")]
        public string FilePath { get; set; }

        [XmlElement(ElementName = "Id")]
        public string FileId { get; set; }

        [XmlElement(ElementName = "Part")]
        public List<string> PartsHash { get; set; } = new List<string>();

        [XmlElement(ElementName = "Send")]
        public int SendAttempts { get; set; } = 0;


        public CloudPartsInfo()
        {
        }
        public CloudPartsInfo(string filePath_)
        {
            FilePath = filePath_;
        }
    }


``
