### ISSUE TITLE
Response parsing exception when downloading a file with slash in name

### ISSUE THREAD

**Issue by phosphene47** [coryrwest/B2.NET#27]
Occurrence:
`IFiles.DownloadByName`
`Files.ParseDownloadResponse`
`Utilities.CheckForErrors`

```csharp
      try
      {
        b2Error = JsonConvert.DeserializeObject<Utilities.B2Error>(result);
      }
```

When downloading a file with a slash in name, e.g. `my/image/2.jpeg`, B2.NET will urlencode it producing `my%2Fimage%2F2.jpeg`.

Backblaze will not accept this and return the following HTML page:
![image](https://user-images.githubusercontent.com/27663662/65482288-ddafc980-dedb-11e9-99d0-2831b426b90e.png)

B2.NET sees the status code as failure and attempts to parse the page as JSON, resulting in a JSON parsing exception.

**Comment by coryrwest** [comment]
This will be fixed in 0.6.2
