### ISSUE TITLE
Ability to get options from the client object, or an upload method that does not require UploadURL

### ISSUE THREAD

**Issue by Atulin** [coryrwest/B2.NET#28]
Currently, file upload is handled with, at minimum
```cs
var client = new B2Client("ACCOUNTID", "APPLICATIONKEY");
var uploadUrl = await client.Files.GetUploadUrl("BUCKETID");
var file = await client.Files.Upload("FILEDATABYTES", "FILENAME", uploadUrl)
```
but the `B2Client` constructor can take `"BUCKETID"` that is required for constructing `uploadUrl`.

Could it not be handled internally, so that the upload can be done with 
```cs
var options = new B2Options() {
	AccountId = "YOUR ACCOUNT ID",
	KeyId = "YOUR APPLICATION KEYID",
	ApplicationKey = "YOUR APPLICATION KEY",
	BucketId = "OPTIONAL BUCKET ID",
	PersistBucket = true/false
};
var client = new B2Client(Options);
var file = await client.Files.Upload("FILEDATABYTES", "FILENAME")
```
?

That would also make it friendlier for dependency injection in ASP.NET, since only `client` would need to be passed, no need to pass any options or config.

Alternatively, maybe something like
```cs
var options = new B2Options() {
	AccountId = "YOUR ACCOUNT ID",
	KeyId = "YOUR APPLICATION KEYID",
	ApplicationKey = "YOUR APPLICATION KEY",
	BucketId = "OPTIONAL BUCKET ID",
	PersistBucket = true/false
};
var client = new B2Client(Options);
var uploadUrl = await client.Files.GetUploadUrl(client.options.BucketId);
var file = await client.Files.Upload("FILEDATABYTES", "FILENAME", uploadUrl)
```
might also do, but I see no point since it can be handled internally.

**Comment by Atulin** [comment]
Can be deleted. Seems like I don't quite understand this library enough to be able to speak of potential issues. Setting it up seems more complex than I initially thought,

**Comment by Atulin** [comment]
On a side note, docs could probably be updated.

```cs
var bucketId = client.AllowedBucketId;
var bucketName = client.AllowedBucketName;
```
doesn't work, authorized or not. And when authorized, upload method does not require the URL.

**Comment by coryrwest** [comment]
Regarding your first comment, BucketId should be optional on all relevant calls in the library. As long as you set PersistBucket in the options to true and set the BucketId on that same options object it will use that "default" bucket.

**Comment by Atulin** [comment]
Yes, I did eventually figure it out. Wasn't clear from the documentation and it was giving me an "incorrect URI" error, but turns out it was due to the B2Client being initialized with plain B2Options, and not with the result of auth.

**Comment by coryrwest** [comment]
Yeah I'm clearing that up right now. I realized after reading your issue how unclear it was.
