### ISSUE TITLE
Display the file in the browser

### ISSUE THREAD

**Issue by insidewill** [coryrwest/B2.NET#32]
to display the file in the browser after get download authorization the only way is to pass via get? Authorization? = ... or we were able to send via header authorization

since now! Thanks

**Comment by coryrwest** [comment]
I'm not sure what you are asking, can you clarify?

**Comment by insidewill** [comment]
I would like to know if while getting "GetDownloadAuthorization" to display the file in the browser (for example an image)

There is a form of this https://files009.backblazeb2.com/file/myBucket/32802f64-fa22-45f0-bc04-953274d1b5a2.jpg?Authorization=3_20191113145732_8165d45b6cbbddb4b7db4b7db4b7db4b7db1d656

Submitting Header Authorization
https://files009.backblazeb2.com/file/myBucket/32802f64-fa22-45f0-bc04-953274d1b5a2.jpg

**Comment by coryrwest** [comment]
If you are talking about downloading the image directly from B2 on the browser, that is outside the scope of this library. This is a server-side library. It doesn't deal with the client at all. How you handle sending authorization headers to B2 from the client is up to you.

**Comment by insidewill** [comment]
Ok! Thaks for support
