### ISSUE TITLE
Would it be possible to update to Newtonsoft.Json v12.0?

### ISSUE THREAD

**Issue by zedseven** [coryrwest/B2.NET#35]
Nuget lists the package as compatible with Newtonsoft.Json >= v9.0, but on calling `B2Client.Authorize` the following exception is thrown:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at B2Net.B2Client.Authorize(B2Options options)
   at B2Net.B2Client..ctor(String keyId, String applicationkey, Int32 requestTimeout)
...
```

Am I missing something, or would it be possible to make it compatible with a newer version of the dependency?

**Comment by coryrwest** [comment]
The dependency is listed as >= version 9.0.1. Are you trying to use it with version 9 or are you trying to use it with a version greater than 9 and it is still not working?
