### ISSUE TITLE
Don't make HTTP Requests during B2Client Construction

### ISSUE THREAD

**Issue by Nikey646** [coryrwest/B2.NET#36]
There may be scenarios where the `B2Client` will be created during a time period where there shouldn't be any HTTP requests being created.

Ideally, the `B2Client.Authorize` wouldn't be called until either the first operation, the first access of `B2Client.Capabilities`, or manually called.

In the event that the Authorize method is called via the first operation it should be done fully async, rather than relying on the `.Result` property of the task. https://github.com/coryrwest/B2.NET/blob/8d0badfdbc32bd1ef5d72752591ea1134b1a7e0b/src/B2Client.cs#L100-L102

As an aside, using `task.Result` is a blocking call, and you use this in Files (via Utilities), Bucket, Authorization, and LargeFiles... This means that the library is not "fully async" as per https://github.com/coryrwest/B2.NET/blob/8d0badfdbc32bd1ef5d72752591ea1134b1a7e0b/README.md#L15 which was quite a shock when I went to check if you were actually running the authorization HTTP request during construction....

In anycase, thank you for the library!

**Comment by coryrwest** [comment]
Oh man. Totally missed that. I'll fix that in the next version.

**Comment by coryrwest** [comment]
This is in version 0.7.2 as a draft feature. You must call Initialize before using if you used the `authorizeOnInitialize` optional parameter. The client will not call it for you.
