### ISSUE TITLE
using an application key and not the master application key 

### ISSUE THREAD

**Issue by omrikaufman** [coryrwest/B2.NET#37]
hi cory,
Happy new year man.
i was wondring i am trying to list the buckets with an application key and not the master application key but i  am getting an error.
i am adding the response i am getting 

waiting for you response

thanks and happy new year 

[B2Net error when no master application key.txt](https://github.com/coryrwest/B2.NET/files/4012975/B2Net.error.when.no.master.application.key.txt)

**Comment by coryrwest** [comment]
I don't have enough information here to help you. Please provide more details. What call did this happen on? Are you sure your applicationKey and applicationKeyId are correct? Are you able to authenticate? Which authenticate method are you using?

**Comment by omrikaufman** [comment]
Hi cory,
Yes i was able to connect. After connectin i am requesting the bucket list
and the i am getting the error.

בתאריך יום ה׳, 2 בינו׳ 2020, 02:11, מאת Cory ‏<notifications@github.com>:

**Comment by coryrwest** [comment]
What is the error you are getting from my library?

**Comment by coryrwest** [comment]
Inactive
