### ISSUE TITLE
Set Content-Type on file upload

### ISSUE THREAD

**Issue by IsaackRasmussen** [coryrwest/B2.NET#39]
Is it possible to add a parameter for Content-Type when uploading files?

**Comment by coryrwest** [comment]
Not at the moment. I will release an update later today with that functionality.

**Comment by coryrwest** [comment]
This is in version 0.7.4

**Comment by IsaackRasmussen** [comment]
That was fast! Thanks!

I installed 0.7.4 but I can't find the Upload() method with ContentType, though I see the changes in code when comparing on Github.

![image](https://user-images.githubusercontent.com/5748784/78592927-18f56280-7846-11ea-8832-a0b90560230f.png)

**Comment by coryrwest** [comment]
Sorry. Forgot to put it on the interface. Stand by.

**Comment by coryrwest** [comment]
0.7.4.1 has the update. Give nuget a couple minutes to validate the package before trying again.

**Comment by IsaackRasmussen** [comment]
Now it builds, thanks again
