### ISSUE TITLE
Support .NET 4.5 and higher

### ISSUE THREAD

**Issue by aboulinguez** [coryrwest/B2.NET#4]
Hi!

Firstly Thanks for you work.

Could you support .NET 4.5 and higher (I have an ASP.NET MVC project working with 4.5.2 for example).

For the moment, I can't install your nuget package into a project targeting .NET 4.5.2.

Thanks in advance !

Best regards.

Antoine.

**Comment by coryrwest** [comment]
Unfortunately, I do not see how that is possible. The library requires System.Security.Cryptography.Algorithms which does not support .NET Standard 1.2 (which would allow for .NET 4.5.1 support). I may look into rolling another SHA1 implementation into the library itself, but I don't have time to undertake such a project at this time.

**Comment by coryrwest** [comment]
I may have found a way to do this.

**Comment by aboulinguez** [comment]
Hi!

Thanks for your answers.

I've tried this morning to migrate your project to .NET Standard 1.2 and see if there is an easy alternative to System.Security.Cryptography.Algorithms but without success (I don't spent too much time on this).

The easiest thing in my case is to migrate my project to .NET 4.6 (not a bad thing at the end). From 4.5.2 it should be not too much effort.

But if you have an easy solution to support .NET 4.5.2 or earlier versions maybe it can allow more people to use your package.

Another question: do you know if it's possible to retrieve the friendly URL of a file after upload? I don't see anything for this in the BackBlaze API. Maybe you can confirm that is just not implemented in their side.

Thanks again for your answers.

Best regards,

Antoine.

**Comment by coryrwest** [comment]
I am currently working on making the package multi-targeted. Hopefully that will allow you to use it. I should have a new version that targets both .NET 4.5 and .NET Standard 1.5 by today.

As for the friendly URL, it is not explicitly supported by the B2 API, but I will look into a way of getting it anyway.

**Comment by coryrwest** [comment]
This is great feedback, thanks.

**Comment by coryrwest** [comment]
This should do it: https://github.com/coryrwest/B2.NET/commit/c029f35cd1325f7319a7a6389c67f399b788800d

I'll be releasing it to nuget as 0.0.2.5

**Comment by aboulinguez** [comment]
I've migrate my project to .NET 4.6 but I've tried your update on a new .NET 4.5.2 project and your v0.0.2.5 package is successfully installed. 

All the best, see you :)

Antoine.
