### ISSUE TITLE
download and upload through streams

### ISSUE THREAD

**Issue by michaellomonosov** [coryrwest/B2.NET#40]
problem with bigfile that all bytes in memory 
httpclient can write to stream directly

**Comment by mattwelke** [comment]
@michaellomonosov Looks like this might be related to https://github.com/coryrwest/B2.NET/issues/6.

**Comment by coryrwest** [comment]
File uploading can now be done with streams. Large Files are next.

**Comment by coryrwest** [comment]
remaining work will be done on https://github.com/coryrwest/B2.NET/issues/43
