### ISSUE TITLE
Generating a download authorization token with a content disposition set fails with B2Exception: "unknown field in com.backblaze.modules.b2.data.DownloadAuthTokenRequest: maxFileCount"

### ISSUE THREAD

**Issue by danports** [coryrwest/B2.NET#41]
The problem is a simple typo [here](https://github.com/coryrwest/B2.NET/blob/5876301d12cb97258afaa22d958b0d341ace2a28/src/Http/RequestGenerators/FileDownloadRequestGenerators.cs#L58): that line should reference `b2ContentDisposition`, not `maxFileCount`.

**Comment by coryrwest** [comment]
Fixed in 0.7.5

**Comment by danports** [comment]
Fix verified. Thanks for the quick response!
