### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by nboltn** [coryrwest/B2.NET#46]
Simply adding this line:

    <PackageReference Include="B2Net" Version="0.7.5"/>

to my `.csproj` file causes all of my frontend api requests to fail:

![api](https://user-images.githubusercontent.com/857940/86199765-ae775a00-baf6-11ea-9cf9-14d5c4242e8c.PNG)

It seems to be messing with the cors policy.

**Comment by coryrwest** [comment]
@nboltn Would you be willing to put together a sample project that demonstrates this? I have been unable to reproduce this.
