### ISSUE TITLE
Folder hierarchy delimiter

### ISSUE THREAD

**Issue by omrikaufman** [coryrwest/B2.NET#8]
hi cory ,
first i would like to say thank you so much - great job man !!!
there is a request about the delimiter .
if i want to make a request from a bucket -  only folders or some different  hierarchy and not all the hierarchy i have to use a delimiter  "/".
i saw that you didn't implement this issue.

backblaze related that issue 
https://www.backblaze.com/b2/docs/b2_list_file_names.html

is there any chance that you will add it soon.. very soon :)
![d](https://user-images.githubusercontent.com/34813765/34327330-11b4480a-e8ca-11e7-90dc-01965ac7c6d3.jpg)

**Comment by coryrwest** [comment]
When I originally wrote this I either missed that, or it wasn't there yet. I was unaware of such a thing. I have some time this week, I'll try to implement it then.

**Comment by omrikaufman** [comment]
Perfect news man . Waiting for update.

**Comment by omrikaufman** [comment]
Hi cory ,
do you have any update ??

**Comment by coryrwest** [comment]
Just released 0.4.5 with this new functionality to nuget.
